import { Property } from '@/types';

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Victorian Family Home',
    address_line_1: 'Marryat Road',
    address_line_2: 'Wimbledon Village',
    city: 'London',
    postcode: 'SW19 5BB',
    description: 'A beautifully presented Victorian family home situated in one of Wimbledon Village\'s most sought-after roads. This exceptional property has been thoughtfully renovated throughout, combining period charm with contemporary living. The generous proportions include a stunning open-plan kitchen and dining area, elegant reception rooms with original fireplaces, and a magnificent south-facing garden backing onto Wimbledon Common.\n\nThe first floor offers five well-appointed bedrooms, including a principal suite with a luxurious en-suite bathroom. Additional highlights include a cellar, off-street parking for two vehicles, and proximity to Wimbledon Village High Street.',
    department: 'sales',
    property_type: 'house',
    price: 2950000,
    price_qualifier: 'OIRO',
    status: 'available',
    bedrooms: 5,
    bathrooms: 4,
    reception_rooms: 2,
    features: [
      'Period features throughout',
      'South-facing garden',
      'Off-street parking for two cars',
      'Moments from Wimbledon Common',
      'Newly renovated kitchen',
      'Four luxurious bathrooms',
      'Cellar with development potential',
      'Walking distance to Village'
    ],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1600&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
    epc_rating: 'C',
    council_tax_band: 'G',
    tenure: 'Freehold',
    featured: true,
    latitude: 51.4340,
    longitude: -0.2133,
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Elegant Village Apartment',
    address_line_1: 'High Street',
    address_line_2: 'Wimbledon Village',
    city: 'London',
    postcode: 'SW19 5EE',
    description: 'A stunning two-bedroom apartment occupying the entire first floor of a handsome period building on Wimbledon Village High Street. This beautifully appointed residence offers generous living spaces with high ceilings, sash windows, and an abundance of natural light.\n\nThe open-plan reception and dining area flows seamlessly into a contemporary kitchen with premium appliances. Both bedrooms benefit from fitted wardrobes, and the principal bedroom has a luxurious en-suite shower room.',
    department: 'lettings',
    property_type: 'flat',
    price: 3250,
    rent_period: 'pcm',
    status: 'available',
    bedrooms: 2,
    bathrooms: 2,
    reception_rooms: 1,
    features: [
      'Heart of Wimbledon Village',
      'High ceilings throughout',
      'Modern kitchen',
      'Two bathrooms',
      'Period features',
      'Abundant natural light'
    ],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=80',
    epc_rating: 'B',
    council_tax_band: 'E',
    featured: true,
    latitude: 51.4347,
    longitude: -0.2142,
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-01-20T10:00:00Z',
  },
  {
    id: '3',
    title: 'Arts & Crafts Family Home',
    address_line_1: 'Burghley Road',
    address_line_2: 'Wimbledon',
    city: 'London',
    postcode: 'SW19 5BH',
    description: 'An exceptional Arts and Crafts family home set behind a private driveway in one of Wimbledon\'s premier residential roads. This remarkable property, extending to approximately 3,800 sq ft, offers generous entertaining spaces, a beautiful mature garden, and a double garage.\n\nThe ground floor features a grand entrance hall, a formal drawing room with inglenook fireplace, a separate dining room, and a stunning kitchen-family room with bi-fold doors to the garden. Upstairs, five bedrooms are arranged over two floors, including a principal suite with dressing room and en-suite.',
    department: 'sales',
    property_type: 'house',
    price: 4250000,
    price_qualifier: 'guide_price',
    status: 'available',
    bedrooms: 5,
    bathrooms: 3,
    reception_rooms: 3,
    features: [
      'Arts and Crafts architecture',
      'Approximately 3,800 sq ft',
      'Private driveway and double garage',
      'Mature landscaped garden',
      'Inglenook fireplace',
      'Kitchen-family room',
      'Principal suite with dressing room',
      'Premier residential road'
    ],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
    epc_rating: 'D',
    council_tax_band: 'H',
    tenure: 'Freehold',
    featured: true,
    latitude: 51.4320,
    longitude: -0.2100,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-02-01T10:00:00Z',
  },
  {
    id: '4',
    title: 'Contemporary Garden Flat',
    address_line_1: 'Woodside',
    address_line_2: 'Wimbledon',
    city: 'London',
    postcode: 'SW19 7AF',
    description: 'A beautifully designed garden flat offering contemporary living in a quiet Wimbledon street. The property benefits from its own private entrance and a delightful south-west facing garden, creating a true sense of seclusion and tranquillity.\n\nThe accommodation comprises an open-plan kitchen and living area with doors to the garden, two double bedrooms, and a stylish bathroom. The finish throughout is of an exceptionally high standard.',
    department: 'lettings',
    property_type: 'flat',
    price: 2450,
    rent_period: 'pcm',
    status: 'available',
    bedrooms: 2,
    bathrooms: 1,
    reception_rooms: 1,
    features: [
      'Private garden',
      'Own entrance',
      'Contemporary design',
      'High specification finish',
      'Quiet residential street',
      'Close to Wimbledon station'
    ],
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600&q=80',
    epc_rating: 'B',
    council_tax_band: 'D',
    featured: false,
    latitude: 51.4280,
    longitude: -0.2080,
    created_at: '2024-02-05T10:00:00Z',
    updated_at: '2024-02-05T10:00:00Z',
  },
  {
    id: '5',
    title: 'Georgian Townhouse',
    address_line_1: 'Church Road',
    address_line_2: 'Wimbledon Village',
    city: 'London',
    postcode: 'SW19 5AG',
    description: 'A magnificent Grade II listed Georgian townhouse positioned in the heart of Wimbledon Village. This exceptional home, dating from the early 19th century, has been meticulously restored to offer the finest in period living with every modern comfort.\n\nThe property extends to over 4,500 sq ft across four floors, with six bedrooms, four reception rooms, and a charming walled garden. Original features include ornate cornicing, marble fireplaces, and elegant sash windows.',
    department: 'sales',
    property_type: 'house',
    price: 6500000,
    price_qualifier: 'OIEO',
    status: 'available',
    bedrooms: 6,
    bathrooms: 5,
    reception_rooms: 4,
    features: [
      'Grade II listed',
      'Over 4,500 sq ft',
      'Six bedrooms',
      'Walled garden',
      'Original period features',
      'Marble fireplaces',
      'Four reception rooms',
      'Heart of the Village'
    ],
    images: [
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
    epc_rating: 'D',
    council_tax_band: 'H',
    tenure: 'Freehold',
    featured: true,
    latitude: 51.4352,
    longitude: -0.2148,
    created_at: '2024-02-10T10:00:00Z',
    updated_at: '2024-02-10T10:00:00Z',
  },
  {
    id: '6',
    title: 'Penthouse Apartment',
    address_line_1: 'Wimbledon Hill Road',
    address_line_2: 'Wimbledon',
    city: 'London',
    postcode: 'SW19 7PA',
    description: 'A breathtaking penthouse apartment with panoramic views across London and Wimbledon Common. This exceptional residence occupies the entire top floor of a prestigious modern development, offering luxurious lateral living across approximately 2,200 sq ft.\n\nThe wraparound terrace provides uninterrupted views, while inside, floor-to-ceiling glazing floods the open-plan living spaces with natural light. The specification includes underfloor heating, a bespoke Italian kitchen, and smart home technology throughout.',
    department: 'sales',
    property_type: 'flat',
    price: 1850000,
    price_qualifier: 'guide_price',
    status: 'under_offer',
    bedrooms: 3,
    bathrooms: 2,
    reception_rooms: 1,
    features: [
      'Penthouse apartment',
      'Panoramic views',
      'Wraparound terrace',
      'Approximately 2,200 sq ft',
      'Smart home technology',
      'Bespoke Italian kitchen',
      'Concierge service',
      'Underground parking'
    ],
    images: [
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1600&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1600&q=80',
    epc_rating: 'B',
    council_tax_band: 'G',
    tenure: 'Leasehold',
    lease_length: 999,
    service_charge: 6500,
    featured: false,
    latitude: 51.4310,
    longitude: -0.2050,
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-02-15T10:00:00Z',
  },
  {
    id: '7',
    title: 'Family Home with Garden',
    address_line_1: 'Lingfield Road',
    address_line_2: 'Wimbledon',
    city: 'London',
    postcode: 'SW19 4QD',
    description: 'A charming four-bedroom semi-detached family home with a wonderful south-facing garden, situated in a popular residential road between Wimbledon Village and Wimbledon town centre. The property offers well-proportioned living spaces and has been tastefully maintained throughout.\n\nThe ground floor provides a bright reception room, a separate dining room, and a kitchen leading to the garden. The first floor accommodates four bedrooms and a family bathroom, while the loft has been converted to provide additional living space.',
    department: 'lettings',
    property_type: 'house',
    price: 4500,
    rent_period: 'pcm',
    status: 'available',
    bedrooms: 4,
    bathrooms: 2,
    reception_rooms: 2,
    features: [
      'South-facing garden',
      'Four bedrooms',
      'Loft conversion',
      'Between Village and town',
      'Well-maintained throughout',
      'Separate dining room'
    ],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
    epc_rating: 'C',
    council_tax_band: 'F',
    featured: false,
    latitude: 51.4300,
    longitude: -0.2060,
    created_at: '2024-02-20T10:00:00Z',
    updated_at: '2024-02-20T10:00:00Z',
  },
  {
    id: '8',
    title: 'Modern Village Studio',
    address_line_1: 'Ridgway',
    address_line_2: 'Wimbledon Village',
    city: 'London',
    postcode: 'SW19 4QW',
    description: 'A beautifully designed studio apartment in a prestigious Wimbledon Village location. This compact yet cleverly appointed residence offers the perfect pied-a-terre or investment opportunity in one of South West London\'s most desirable postcodes.\n\nThe open-plan living space incorporates a contemporary kitchenette, a sleeping area, and a stylish shower room. Large windows provide excellent natural light, and the property benefits from communal gardens.',
    department: 'lettings',
    property_type: 'studio',
    price: 1450,
    rent_period: 'pcm',
    status: 'let_agreed',
    bedrooms: 0,
    bathrooms: 1,
    features: [
      'Wimbledon Village location',
      'Contemporary design',
      'Communal gardens',
      'Excellent natural light',
      'Perfect pied-a-terre'
    ],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=80',
    epc_rating: 'C',
    council_tax_band: 'C',
    featured: false,
    latitude: 51.4355,
    longitude: -0.2160,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-03-01T10:00:00Z',
  },
  {
    id: '9',
    title: 'Detached Edwardian Residence',
    address_line_1: 'Parkside',
    address_line_2: 'Wimbledon Common',
    city: 'London',
    postcode: 'SW19 5NE',
    description: 'A magnificent detached Edwardian residence commanding an enviable position overlooking Wimbledon Common. This grand family home, extending to approximately 5,200 sq ft, offers expansive living spaces, a beautiful garden, and direct access to the Common.\n\nThe property retains exceptional original features including ornate plasterwork, stained glass windows, and a grand staircase. The house has been sympathetically updated with modern systems while preserving its architectural heritage.',
    department: 'sales',
    property_type: 'house',
    price: 5750000,
    price_qualifier: 'OIRO',
    status: 'available',
    bedrooms: 7,
    bathrooms: 5,
    reception_rooms: 4,
    features: [
      'Overlooking Wimbledon Common',
      'Approximately 5,200 sq ft',
      'Detached Edwardian',
      'Direct Common access',
      'Seven bedrooms',
      'Grand staircase',
      'Stained glass windows',
      'Landscaped garden'
    ],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1600&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
    epc_rating: 'D',
    council_tax_band: 'H',
    tenure: 'Freehold',
    featured: true,
    latitude: 51.4370,
    longitude: -0.2200,
    created_at: '2024-03-05T10:00:00Z',
    updated_at: '2024-03-05T10:00:00Z',
  },
];

export const mockTestimonials = [
  {
    id: '1',
    quote: 'Elizabeth provided an outstanding service from start to finish. Her knowledge of Wimbledon Village is unmatched, and her personal approach made the entire process seamless.',
    name: 'James & Sarah H.',
    role: 'Sold a family home in Wimbledon Village',
  },
  {
    id: '2',
    quote: 'We were relocating from overseas and Elizabeth went above and beyond to find us the perfect family home. Her dedication and local expertise were invaluable.',
    name: 'The Mortensen Family',
    role: 'Purchased via Elizabeth Wightwick',
  },
  {
    id: '3',
    quote: 'As a landlord with multiple properties, I trust Elizabeth implicitly. Her management service is thorough, professional, and always has my best interests at heart.',
    name: 'Dr. Richard P.',
    role: 'Landlord, three properties in SW19',
  },
  {
    id: '4',
    quote: 'The bespoke service is what sets Elizabeth apart. She truly listens to what you need and delivers with quiet professionalism. We could not recommend her more highly.',
    name: 'Catherine & Mark W.',
    role: 'Found their dream home in Wimbledon',
  },
];
