import { Property } from '@/types';

const cdnBase = 'https://cdns3.estateweb.com/assets/9603/of/4/pro';

function imgRange(ref: string, count: number, max = 6): string[] {
  return Array.from({ length: Math.min(count, max) }, (_, i) => `${cdnBase}/${ref}/main/${i + 1}.jpg`);
}

export const mockProperties: Property[] = [
  // ===== SALES =====
  {
    id: 'ew-s-250',
    title: 'Ellerton Road',
    address_line_1: 'Ellerton Road',
    city: 'London',
    postcode: 'SW20 0EW',
    description: 'An impressive 5,005 square feet of luxurious living space set on a private road ensuring exclusivity and tranquillity. This exquisite detached family home features high-end finishes throughout with generous proportions across multiple floors.\n\nThe property offers five beautifully appointed bedrooms, four bathrooms, and three elegant reception rooms. Situated in a sought-after location with convenient access to local amenities, outstanding schools, and excellent transport links.',
    department: 'sales',
    property_type: 'house',
    price: 6595000,
    price_qualifier: 'fixed',
    status: 'available',
    bedrooms: 5,
    bathrooms: 4,
    reception_rooms: 3,
    features: [
      '5,005 sq ft of living space',
      'Private road setting',
      'High-end finishes throughout',
      'Chain free',
      'Five generous bedrooms',
      'Three elegant reception rooms',
      'Beautifully landscaped grounds',
      'Excellent transport links',
    ],
    images: imgRange('34407374', 32),
    main_image: `${cdnBase}/34407374/main/1.jpg`,
    floor_plan_url: `${cdnBase}/34407374/floorplans/1.jpg`,
    tenure: 'Freehold',
    featured: true,
    latitude: 51.4178,
    longitude: -0.2242,
    created_at: '2025-01-10T10:00:00Z',
    updated_at: '2025-01-10T10:00:00Z',
  },
  {
    id: 'ew-s-247',
    title: 'Copse Hill',
    address_line_1: 'Copse Hill',
    city: 'London',
    postcode: 'SW20 0NN',
    description: 'Nestled in the desirable area of Copse Hill, Wimbledon, this stunning detached house offers an impressive blend of modern living and spacious comfort. Built in 2017 and completely refurbished in 2024, the home spans approximately 3,992 square feet with five en-suite bedrooms and two reception rooms.\n\nThe property features a self-contained annexe, heated outdoor swimming pool measuring 10.5 metres, and a garden with BBQ terrace. Modern amenities include underfloor heating, air conditioning, Sonos music system, and gated parking with electric car charging.',
    department: 'sales',
    property_type: 'house',
    price: 5950000,
    price_qualifier: 'OIRO',
    status: 'available',
    bedrooms: 5,
    bathrooms: 5,
    reception_rooms: 2,
    features: [
      'Approximately 3,992 sq ft',
      'Built 2017, refurbished 2024',
      'Heated 10.5m swimming pool',
      'Self-contained annexe',
      'Underfloor heating & air conditioning',
      'Gated parking with EV charging',
      'Sonos music system throughout',
      '8,000 sq ft total land area',
    ],
    images: imgRange('34365370', 40),
    main_image: `${cdnBase}/34365370/main/1.jpg`,
    floor_plan_url: `${cdnBase}/34365370/floorplans/1.jpg`,
    tenure: 'Freehold',
    featured: true,
    latitude: 51.4230,
    longitude: -0.2310,
    created_at: '2024-12-15T10:00:00Z',
    updated_at: '2024-12-15T10:00:00Z',
  },
  {
    id: 'ew-s-246',
    title: 'Linkside',
    address_line_1: 'Linkside',
    city: 'New Malden',
    postcode: 'KT3 4LB',
    description: 'An impressive detached house offering a perfect blend of space, comfort, and convenience spanning 2,793 square feet. The main residence contains four bedrooms and two bathrooms, complemented by a separate one-bedroom guest annexe with its own reception area, mezzanine, kitchen, and bathroom.\n\nThe property benefits from an undercover entertaining area perfect for alfresco dining, ample off-street parking, a double garage, and generous garden space. Excellent transport links to London and proximity to outstanding schools.',
    department: 'sales',
    property_type: 'house',
    price: 1750000,
    price_qualifier: 'OIEO',
    status: 'available',
    bedrooms: 5,
    bathrooms: 3,
    reception_rooms: 4,
    features: [
      '2,793 sq ft of living space',
      'Separate one-bedroom annexe',
      'Double garage',
      'Undercover entertaining area',
      'Ample off-street parking',
      'Mezzanine space',
      'Excellent transport links',
      'Near outstanding schools',
    ],
    images: imgRange('34361420', 24),
    main_image: `${cdnBase}/34361420/main/1.jpg`,
    floor_plan_url: `${cdnBase}/34361420/floorplans/1.jpg`,
    tenure: 'Freehold',
    featured: true,
    latitude: 51.3920,
    longitude: -0.2550,
    created_at: '2024-12-01T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'ew-s-225',
    title: 'Poplar Grove',
    address_line_1: 'Poplar Grove',
    city: 'New Malden',
    postcode: 'KT3 3DE',
    description: 'A rare to the market four-bedroom Victorian house blending period features with contemporary practicality. Built in 1900, this characterful property spans approximately 1,500 square feet in the sought-after Groves area of New Malden.\n\nThe property features two spacious reception rooms, a well-appointed kitchen, and a magnificent 100-foot garden with a built-in garden room suitable for use as a home office or gym. Off-street parking for one vehicle and proximity to both Richmond Park and Wimbledon Common.',
    department: 'sales',
    property_type: 'house',
    price: 1200000,
    price_qualifier: 'OIRO',
    status: 'under_offer',
    bedrooms: 4,
    bathrooms: 2,
    reception_rooms: 2,
    features: [
      'Victorian character, built 1900',
      '100 ft garden with garden room',
      'Two spacious reception rooms',
      'Off-street parking',
      'Chain free',
      'Near Richmond Park & Wimbledon Common',
      'Sought-after Groves area',
      'Approximately 1,500 sq ft',
    ],
    images: imgRange('33829021', 25),
    main_image: `${cdnBase}/33829021/main/1.jpg`,
    tenure: 'Freehold',
    featured: false,
    latitude: 51.3930,
    longitude: -0.2580,
    created_at: '2024-06-10T10:00:00Z',
    updated_at: '2024-11-20T10:00:00Z',
  },
  {
    id: 'ew-s-251',
    title: 'Myrtle Grove',
    address_line_1: 'Myrtle Grove',
    city: 'New Malden',
    postcode: 'KT3 3LF',
    description: 'A spacious and beautifully presented mid-terrace five-bedroom family home offering an open-plan kitchen and dining area, a separate reception room, and a charming garden with log cabin outbuilding.\n\nThe accommodation includes a ground-floor reception room with feature fireplace, a contemporary open-plan kitchen-diner, and five bedrooms arranged over two floors. The garden features a wood-decked terrace and a log cabin with electricity, suitable for use as a gym or home office.',
    department: 'sales',
    property_type: 'house',
    price: 995000,
    price_qualifier: 'OIEO',
    status: 'available',
    bedrooms: 5,
    bathrooms: 3,
    reception_rooms: 2,
    features: [
      'Five bedrooms',
      'Open-plan kitchen/dining room',
      'Log cabin with electricity',
      'Wood-decked terrace',
      'Feature fireplace',
      'Off-street parking',
      'Near Richmond Park',
      'Excellent schools nearby',
    ],
    images: imgRange('34420620', 13),
    main_image: `${cdnBase}/34420620/main/1.jpg`,
    featured: false,
    latitude: 51.3935,
    longitude: -0.2570,
    created_at: '2025-01-20T10:00:00Z',
    updated_at: '2025-01-20T10:00:00Z',
  },
  {
    id: 'ew-s-200',
    title: 'Chestnut Grove',
    address_line_1: 'Chestnut Grove',
    city: 'New Malden',
    postcode: 'KT3 3JT',
    description: 'A charming terraced house in the sought-after Groves area featuring a spacious reception room at the front and an open-plan kitchen and dining area leading to the garden. The property includes three double bedrooms, three modern bathrooms, and a versatile garden room.\n\nThe garden room offers excellent potential as a home gym or office. Situated close to outstanding schools with strong transport links to Central London and easy access to the A3.',
    department: 'sales',
    property_type: 'house',
    price: 895000,
    price_qualifier: 'fixed',
    status: 'sold',
    bedrooms: 3,
    bathrooms: 3,
    reception_rooms: 2,
    features: [
      'Three double bedrooms',
      'Three modern bathrooms',
      'Open-plan kitchen/dining area',
      'Garden room (gym/office)',
      'Beautiful garden',
      'Outstanding schools nearby',
      'Strong transport links',
      'Easy A3 access',
    ],
    images: imgRange('33377176', 18),
    main_image: `${cdnBase}/33377176/main/1.jpg`,
    floor_plan_url: `${cdnBase}/33377176/floorplans/1.jpg`,
    featured: false,
    latitude: 51.3940,
    longitude: -0.2565,
    created_at: '2024-03-15T10:00:00Z',
    updated_at: '2024-09-10T10:00:00Z',
    sold_let_date: '2024-09-10T10:00:00Z',
  },
  {
    id: 'ew-s-228',
    title: 'Poplar Grove',
    address_line_1: 'Poplar Grove',
    city: 'New Malden',
    postcode: 'KT3 3DG',
    description: 'A well-presented three-bedroom semi-detached family home situated in the popular Groves area of New Malden. This property offers two reception rooms, a fitted kitchen, and a private rear garden with off-street parking.\n\nConveniently located for local shops, schools, and transport links, this home provides an excellent opportunity for families seeking a move to one of Surrey\'s most desirable residential areas.',
    department: 'sales',
    property_type: 'house',
    price: 865000,
    price_qualifier: 'fixed',
    status: 'available',
    bedrooms: 3,
    bathrooms: 1,
    reception_rooms: 2,
    features: [
      'Semi-detached family home',
      'Two reception rooms',
      'Private rear garden',
      'Off-street parking',
      'Popular Groves area',
      'Close to schools & shops',
    ],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
    tenure: 'Freehold',
    featured: false,
    latitude: 51.3932,
    longitude: -0.2578,
    created_at: '2024-08-05T10:00:00Z',
    updated_at: '2024-08-05T10:00:00Z',
  },
  {
    id: 'ew-s-237',
    title: 'Poplar Grove',
    address_line_1: 'Poplar Grove',
    city: 'New Malden',
    postcode: 'KT3 3DF',
    description: 'A four-bedroom terraced family home in the desirable Groves area offering generous living accommodation across three floors. The property features two reception rooms, a modern kitchen, and a private garden.\n\nWell-positioned for access to excellent local schools, parks, and New Malden\'s thriving high street, this home represents outstanding value in one of the area\'s most popular residential streets.',
    department: 'sales',
    property_type: 'house',
    price: 790000,
    price_qualifier: 'OIRO',
    status: 'available',
    bedrooms: 4,
    bathrooms: 2,
    reception_rooms: 2,
    features: [
      'Four-bedroom terraced home',
      'Two reception rooms',
      'Modern kitchen',
      'Private garden',
      'Desirable Groves area',
      'Near excellent schools',
    ],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
    tenure: 'Freehold',
    featured: false,
    latitude: 51.3933,
    longitude: -0.2575,
    created_at: '2024-10-15T10:00:00Z',
    updated_at: '2024-10-15T10:00:00Z',
  },
  {
    id: 'ew-s-232',
    title: 'Salisbury Road',
    address_line_1: 'Salisbury Road',
    city: 'New Malden',
    postcode: 'KT3 3NG',
    description: 'An attractive three-bedroom end-of-terrace family home benefiting from three bathrooms and two reception rooms. The property has been well maintained throughout and offers comfortable family living in a convenient New Malden location.\n\nClose to local shops, parks, and excellent transport links including New Malden station with direct services to Waterloo. The property also benefits from a private rear garden and off-street parking.',
    department: 'sales',
    property_type: 'house',
    price: 725000,
    price_qualifier: 'fixed',
    status: 'available',
    bedrooms: 3,
    bathrooms: 3,
    reception_rooms: 2,
    features: [
      'End-of-terrace family home',
      'Three bathrooms',
      'Two reception rooms',
      'Private rear garden',
      'Off-street parking',
      'Close to New Malden station',
    ],
    images: [
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
    tenure: 'Freehold',
    featured: false,
    latitude: 51.3950,
    longitude: -0.2530,
    created_at: '2024-09-01T10:00:00Z',
    updated_at: '2024-09-01T10:00:00Z',
  },
  {
    id: 'ew-s-206',
    title: 'The Ridgway',
    address_line_1: 'The Ridgway',
    city: 'London',
    postcode: 'SW19 4SF',
    description: 'A well-located two-bedroom top-floor flat in a prestigious block on The Ridgway, Wimbledon Village. The property offers two double bedrooms, a large living room with balcony, a modern bathroom, and a fitted kitchen.\n\nThe flat benefits from a garage, a prime Wimbledon Village location, and is offered chain free. An excellent opportunity in one of South West London\'s most prestigious addresses.',
    department: 'sales',
    property_type: 'flat',
    price: 575000,
    price_qualifier: 'fixed',
    status: 'under_offer',
    bedrooms: 2,
    bathrooms: 1,
    reception_rooms: 1,
    features: [
      'Top-floor flat',
      'Prestigious Wimbledon Village block',
      'Balcony',
      'Garage included',
      'Chain free',
      'Prime location',
    ],
    images: imgRange('33414946', 6),
    main_image: `${cdnBase}/33414946/main/1.jpg`,
    floor_plan_url: `${cdnBase}/33414946/floorplans/1.png`,
    tenure: 'Leasehold',
    featured: false,
    latitude: 51.4350,
    longitude: -0.2160,
    created_at: '2024-04-20T10:00:00Z',
    updated_at: '2024-11-15T10:00:00Z',
  },
  {
    id: 'ew-s-215',
    title: 'Smeaton Road',
    address_line_1: 'Smeaton Road',
    city: 'London',
    postcode: 'SW18 5JH',
    description: 'A superb two-bedroom ground-floor flat in Southfields featuring an open-plan kitchen, dining, and reception area with breakfast bar. The property includes two spacious bedrooms, a modern bathroom, and benefits from shared rear garden access and a private courtyard with storage shed.\n\nPositioned just 0.4 miles from Southfields tube station, the flat also offers share of freehold and potential for extension subject to planning permission.',
    department: 'sales',
    property_type: 'flat',
    price: 528500,
    price_qualifier: 'fixed',
    status: 'under_offer',
    bedrooms: 2,
    bathrooms: 1,
    reception_rooms: 1,
    features: [
      'Ground-floor flat',
      'Share of freehold',
      'Private courtyard',
      'Shared rear garden',
      '0.4 miles to Southfields tube',
      'Extension potential (STPP)',
    ],
    images: imgRange('33639883', 11),
    main_image: `${cdnBase}/33639883/main/1.jpg`,
    floor_plan_url: `${cdnBase}/33639883/floorplans/1.png`,
    tenure: 'Share of Freehold',
    featured: false,
    latitude: 51.4445,
    longitude: -0.2060,
    created_at: '2024-05-10T10:00:00Z',
    updated_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 'ew-s-171',
    title: 'Poplar Grove',
    address_line_1: 'Poplar Grove',
    city: 'New Malden',
    postcode: 'KT3 3DA',
    description: 'A well-presented two-bedroom maisonette in the popular Groves area of New Malden. The property offers a bright reception room, a fitted kitchen, two double bedrooms, and a modern bathroom.\n\nConveniently located close to New Malden\'s amenities, local parks, and excellent transport links. An ideal opportunity for first-time buyers or investors seeking a home in a sought-after residential area.',
    department: 'sales',
    property_type: 'flat',
    price: 485000,
    price_qualifier: 'fixed',
    status: 'available',
    bedrooms: 2,
    bathrooms: 1,
    reception_rooms: 1,
    features: [
      'Two-bedroom maisonette',
      'Popular Groves area',
      'Bright reception room',
      'Modern bathroom',
      'Close to amenities',
      'Excellent transport links',
    ],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=80',
    tenure: 'Leasehold',
    featured: false,
    latitude: 51.3928,
    longitude: -0.2582,
    created_at: '2024-01-05T10:00:00Z',
    updated_at: '2024-01-05T10:00:00Z',
  },

  // ===== LETTINGS =====
  {
    id: 'ew-l-222',
    title: 'Lincoln Avenue',
    address_line_1: 'Lincoln Avenue',
    city: 'London',
    postcode: 'SW19 5JT',
    description: 'An impressive 6,378 square feet of luxurious living space in this stunning detached family home built in 2021. The property features modern design and high-quality finishes throughout with six generously proportioned bedrooms, five bathrooms, and five reception rooms.\n\nExceptional amenities include a private cinema room, sauna, and beautifully landscaped grounds. Situated in a prime Wimbledon location providing easy access to local amenities, excellent schools, and transport links.',
    department: 'lettings',
    property_type: 'house',
    price: 23000,
    rent_period: 'pcm',
    status: 'available',
    bedrooms: 6,
    bathrooms: 5,
    reception_rooms: 5,
    features: [
      '6,378 sq ft of living space',
      'Built 2021',
      'Private cinema room',
      'Sauna',
      'Six generous bedrooms',
      'Five reception rooms',
      'Landscaped grounds',
      'Prime Wimbledon location',
    ],
    images: imgRange('33767440', 17),
    main_image: `${cdnBase}/33767440/main/1.jpg`,
    floor_plan_url: `${cdnBase}/33767440/floorplans/1.jpg`,
    featured: true,
    latitude: 51.4280,
    longitude: -0.2180,
    created_at: '2024-11-01T10:00:00Z',
    updated_at: '2024-11-01T10:00:00Z',
  },
  {
    id: 'ew-l-192',
    title: 'Lincoln Avenue',
    address_line_1: 'Lincoln Avenue',
    address_line_2: 'Wimbledon',
    city: 'London',
    postcode: 'SW19 5JT',
    description: 'A magnificent new-build detached family home on one of Wimbledon\'s most prestigious residential avenues. This exceptional six-bedroom property offers luxurious contemporary living across generous proportions with the highest specification throughout.\n\nThe home features four modern bathrooms, expansive entertaining spaces, and a beautiful private garden. Perfectly positioned for Wimbledon Village amenities, excellent schools, and direct transport links to Central London.',
    department: 'lettings',
    property_type: 'house',
    price: 21000,
    rent_period: 'pcm',
    status: 'let_agreed',
    bedrooms: 6,
    bathrooms: 4,
    reception_rooms: 3,
    features: [
      'New-build detached home',
      'Six bedrooms',
      'Four modern bathrooms',
      'Contemporary specification',
      'Private garden',
      'Prestigious avenue',
      'Near Wimbledon Village',
      'Excellent schools nearby',
    ],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
    featured: false,
    latitude: 51.4282,
    longitude: -0.2185,
    created_at: '2024-04-01T10:00:00Z',
    updated_at: '2024-08-15T10:00:00Z',
  },
  {
    id: 'ew-l-178',
    title: 'Malcolm Road',
    address_line_1: 'Malcolm Road',
    city: 'London',
    postcode: 'SW19 4AS',
    description: 'A substantial detached family home in a highly sought-after Wimbledon location. This impressive six-bedroom property offers generous living accommodation with elegant reception rooms, a modern kitchen, and beautiful private gardens.\n\nThe property benefits from off-street parking, a double garage, and is conveniently located for Wimbledon Village, the Common, and excellent local schools.',
    department: 'lettings',
    property_type: 'house',
    price: 20000,
    rent_period: 'pcm',
    status: 'let_agreed',
    bedrooms: 6,
    bathrooms: 4,
    reception_rooms: 3,
    features: [
      'Substantial detached home',
      'Six bedrooms',
      'Double garage',
      'Private gardens',
      'Off-street parking',
      'Near Wimbledon Common',
    ],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
    featured: false,
    latitude: 51.4295,
    longitude: -0.2100,
    created_at: '2024-02-15T10:00:00Z',
    updated_at: '2024-06-01T10:00:00Z',
  },
  {
    id: 'ew-l-249',
    title: 'Ellerton Road',
    address_line_1: 'Ellerton Road',
    city: 'London',
    postcode: 'SW20 0EW',
    description: 'An exquisite detached family home featuring 5,005 square feet of living space situated on a private road in a prestigious London location. The property emphasises luxury finishes and tranquillity, offering five generous bedrooms, three bathrooms, and three reception rooms.\n\nSet on a private road ensuring exclusivity, with easy access to local amenities, schools, and transport links. Available from June 2026.',
    department: 'lettings',
    property_type: 'house',
    price: 20000,
    rent_period: 'pcm',
    status: 'available',
    bedrooms: 5,
    bathrooms: 4,
    reception_rooms: 3,
    features: [
      '5,005 sq ft of living space',
      'Private road setting',
      'High-end finishes',
      'Five generous bedrooms',
      'Three reception rooms',
      'Available June 2026',
      'Beautifully landscaped grounds',
      'Excellent transport links',
    ],
    images: imgRange('34404175', 32),
    main_image: `${cdnBase}/34404175/main/1.jpg`,
    featured: true,
    latitude: 51.4178,
    longitude: -0.2245,
    created_at: '2025-01-15T10:00:00Z',
    updated_at: '2025-01-15T10:00:00Z',
  },
  {
    id: 'ew-l-196',
    title: 'Parkside Avenue',
    address_line_1: 'Parkside Avenue',
    city: 'London',
    postcode: 'SW19 5ES',
    description: 'A stunning detached house offering the perfect blend of luxury and comfort. The property features contemporary open-plan kitchen and family areas, a private gym, and a fantastic landscaped garden perfect for enjoying the outdoors.\n\nSpanning 2,971 square feet, the home includes five bedrooms with the master suite featuring a dressing room and en-suite, four bathrooms, three reception rooms, and a large hallway with ample storage.',
    department: 'lettings',
    property_type: 'house',
    price: 16500,
    rent_period: 'pcm',
    status: 'available',
    bedrooms: 5,
    bathrooms: 4,
    reception_rooms: 3,
    features: [
      '2,971 sq ft of living space',
      'Private gym',
      'Landscaped garden',
      'Master with dressing room & en-suite',
      'Open-plan kitchen/family room',
      'Five bedrooms',
      'Four bathrooms',
      'Ample storage throughout',
    ],
    images: imgRange('33311477', 22),
    main_image: `${cdnBase}/33311477/main/1.jpg`,
    featured: false,
    latitude: 51.4310,
    longitude: -0.2220,
    created_at: '2024-01-08T10:00:00Z',
    updated_at: '2024-01-08T10:00:00Z',
  },
  {
    id: 'ew-l-213',
    title: 'Lancaster Road',
    address_line_1: 'Lancaster Road',
    city: 'London',
    postcode: 'SW19 5DE',
    description: 'An impressive semi-detached family home in a prime Wimbledon location. This six-bedroom property offers generous proportions with four bathrooms, elegant reception rooms, and a beautiful garden.\n\nThe property is perfectly positioned for Wimbledon Village amenities, local parks, and excellent schools. Direct transport links provide easy access to Central London.',
    department: 'lettings',
    property_type: 'house',
    price: 15500,
    rent_period: 'pcm',
    status: 'available',
    bedrooms: 6,
    bathrooms: 4,
    reception_rooms: 2,
    features: [
      'Semi-detached family home',
      'Six bedrooms',
      'Four bathrooms',
      'Beautiful garden',
      'Prime Wimbledon location',
      'Near Wimbledon Village',
    ],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
    featured: false,
    latitude: 51.4305,
    longitude: -0.2115,
    created_at: '2024-07-10T10:00:00Z',
    updated_at: '2024-07-10T10:00:00Z',
  },
  {
    id: 'ew-l-127',
    title: 'Beltane Drive',
    address_line_1: 'Beltane Drive',
    address_line_2: 'Wimbledon Village',
    city: 'London',
    postcode: 'SW19 5JN',
    description: 'A handsome detached property in the heart of Wimbledon Village offering five bedrooms, four bathrooms, and generous entertaining spaces. The property features a beautiful mature garden and off-street parking.\n\nIdeally positioned on a quiet residential drive just moments from Wimbledon Village High Street, the Common, and outstanding local schools.',
    department: 'lettings',
    property_type: 'house',
    price: 14000,
    rent_period: 'pcm',
    status: 'let_agreed',
    bedrooms: 5,
    bathrooms: 4,
    reception_rooms: 2,
    features: [
      'Detached Wimbledon Village home',
      'Five bedrooms',
      'Mature garden',
      'Off-street parking',
      'Near Village High Street',
      'Close to Wimbledon Common',
    ],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
    featured: false,
    latitude: 51.4330,
    longitude: -0.2190,
    created_at: '2023-10-01T10:00:00Z',
    updated_at: '2024-03-15T10:00:00Z',
  },
  {
    id: 'ew-l-242',
    title: 'St. Mary\'s Road',
    address_line_1: 'St. Mary\'s Road',
    city: 'London',
    postcode: 'SW19 7BZ',
    description: 'Nestled on the prestigious St. Mary\'s Road in London, this impressive detached house offers a perfect blend of modern living and spacious comfort. Built in 2010, the property spans 3,638 square feet across three storeys with five bedrooms, three bathrooms, and three reception rooms.\n\nThe home includes a formal dining room, off-street parking, and a beautifully landscaped garden. Ideally located near Wimbledon Village with convenient access to amenities and transport.',
    department: 'lettings',
    property_type: 'house',
    price: 12500,
    rent_period: 'pcm',
    status: 'available',
    bedrooms: 5,
    bathrooms: 3,
    reception_rooms: 3,
    features: [
      '3,638 sq ft across three storeys',
      'Built 2010',
      'Formal dining room',
      'Off-street parking',
      'Landscaped garden',
      'Five bedrooms',
      'Three reception rooms',
      'Near Wimbledon Village',
    ],
    images: imgRange('34244275', 24),
    main_image: `${cdnBase}/34244275/main/1.jpg`,
    featured: false,
    latitude: 51.4275,
    longitude: -0.2080,
    created_at: '2024-10-01T10:00:00Z',
    updated_at: '2024-10-01T10:00:00Z',
  },
  {
    id: 'ew-l-195',
    title: 'Arterberry Road',
    address_line_1: 'Arterberry Road',
    city: 'London',
    postcode: 'SW20 8AH',
    description: 'An elegant five-bedroom residence in the heart of Wimbledon Village offering generous living accommodation across beautifully proportioned rooms. The property features four bathrooms, three reception rooms, and a stunning private garden.\n\nSituated on one of Wimbledon\'s most desirable residential roads, moments from the Village High Street, Wimbledon Common, and excellent local schools.',
    department: 'lettings',
    property_type: 'house',
    price: 12000,
    rent_period: 'pcm',
    status: 'let_agreed',
    bedrooms: 5,
    bathrooms: 4,
    reception_rooms: 3,
    features: [
      'Wimbledon Village location',
      'Five bedrooms',
      'Four bathrooms',
      'Stunning private garden',
      'Three reception rooms',
      'Near Village High Street',
    ],
    images: [
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
    featured: false,
    latitude: 51.4265,
    longitude: -0.2230,
    created_at: '2024-03-20T10:00:00Z',
    updated_at: '2024-07-10T10:00:00Z',
  },
  {
    id: 'ew-l-190',
    title: 'Greenoak Way',
    address_line_1: 'Greenoak Way',
    city: 'London',
    postcode: 'SW19 5NX',
    description: 'A magnificent seven-bedroom detached house situated directly across from Wimbledon Common. This exceptional family home offers seven bathrooms, three reception rooms, and expansive living accommodation throughout.\n\nThe property provides a rare combination of space, privacy, and an unrivalled location. Beautifully maintained gardens and off-street parking complete this outstanding family residence.',
    department: 'lettings',
    property_type: 'house',
    price: 10000,
    rent_period: 'pcm',
    status: 'let_agreed',
    bedrooms: 7,
    bathrooms: 7,
    reception_rooms: 3,
    features: [
      'Seven bedrooms, seven bathrooms',
      'Directly opposite Wimbledon Common',
      'Three reception rooms',
      'Detached family home',
      'Beautifully maintained gardens',
      'Off-street parking',
    ],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
    featured: false,
    latitude: 51.4360,
    longitude: -0.2200,
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2024-05-20T10:00:00Z',
  },
  {
    id: 'ew-l-236',
    title: 'Cottenham Drive',
    address_line_1: 'Cottenham Drive',
    city: 'London',
    postcode: 'SW20 0DQ',
    description: 'A well-presented four-bedroom end-of-terrace house in a popular Wimbledon location. The property offers a bright reception room, a modern kitchen, four bedrooms, and two bathrooms. A private rear garden completes the accommodation.\n\nConveniently located with easy access to Raynes Park station, local shops, and parks. An ideal family home in a well-connected residential area.',
    department: 'lettings',
    property_type: 'house',
    price: 5500,
    rent_period: 'pcm',
    status: 'let_agreed',
    bedrooms: 4,
    bathrooms: 2,
    reception_rooms: 1,
    features: [
      'End-of-terrace house',
      'Four bedrooms',
      'Private rear garden',
      'Modern kitchen',
      'Near Raynes Park station',
      'Well-connected location',
    ],
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
    featured: false,
    latitude: 51.4150,
    longitude: -0.2200,
    created_at: '2024-09-15T10:00:00Z',
    updated_at: '2024-11-01T10:00:00Z',
  },
  {
    id: 'ew-l-183',
    title: 'Beechcroft Avenue',
    address_line_1: 'Beechcroft Avenue',
    city: 'New Malden',
    postcode: 'KT3 3BN',
    description: 'A spacious five-bedroom semi-detached family home in a popular New Malden location. The property offers two reception rooms, two bathrooms, a fitted kitchen, and a generous rear garden.\n\nWell-positioned for local schools, New Malden\'s shopping amenities, and transport links with direct services to Waterloo. An excellent family home with scope to personalise.',
    department: 'lettings',
    property_type: 'house',
    price: 4000,
    rent_period: 'pcm',
    status: 'let_agreed',
    bedrooms: 5,
    bathrooms: 2,
    reception_rooms: 2,
    features: [
      'Five-bedroom semi-detached',
      'Two reception rooms',
      'Generous rear garden',
      'Near New Malden station',
      'Close to schools',
      'Scope to personalise',
    ],
    images: [
      'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
    ],
    main_image: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=1600&q=80',
    featured: false,
    latitude: 51.3945,
    longitude: -0.2560,
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-05-15T10:00:00Z',
  },
];

export const mockTestimonials = [
  {
    id: '1',
    quote: 'Elizabeth provided an outstanding service from start to finish. Her knowledge of Wimbledon Village is unmatched, and her personal approach made the entire process seamless.',
    name: 'James & Sarah H.',
    role: 'Sold a family home in Wimbledon Village',
  },
  {
    id: '2',
    quote: 'We were relocating from overseas and Elizabeth went above and beyond to find us the perfect family home. Her dedication and local expertise were invaluable.',
    name: 'The Mortensen Family',
    role: 'Purchased via Elizabeth Wightwick',
  },
  {
    id: '3',
    quote: 'As a landlord with multiple properties, I trust Elizabeth implicitly. Her management service is thorough, professional, and always has my best interests at heart.',
    name: 'Dr. Richard P.',
    role: 'Landlord, three properties in SW19',
  },
  {
    id: '4',
    quote: 'The bespoke service is what sets Elizabeth apart. She truly listens to what you need and delivers with quiet professionalism. We could not recommend her more highly.',
    name: 'Catherine & Mark W.',
    role: 'Found their dream home in Wimbledon',
  },
];
